version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env.example
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE=http://backend:4000
